tasks:
  - name: AWS
    command: |
      curl -fSsl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
      unzip -qq awscliv2.zip
      sudo ./aws/install --update
      rm awscliv2.zip
  - name: python
    command: |
      python -m pip install --upgrade virtualenv
      python -m pip install --upgrade pip
      python -m pip install --upgrade virtualenv
  - name: cdk    
      npm i -g aws-cdk
      pip install --upgrade aws-cdk.core
